# Generated by Django 4.2.5 on 2024-05-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_transaction_bookquantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookquantity",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quantity",
                to="webapp.book",
            ),
        ),
    ]
