# Generated by Django 5.0.4 on 2024-05-09 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_booktag'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_tags',
            field=models.ManyToManyField(to='webapp.tag'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_item', to='webapp.book'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to='webapp.user'),
        ),
        migrations.DeleteModel(
            name='BookTag',
        ),
    ]
